# SPDX-License-Identifier: MIT-0
# SPDX-FileCopyrightText: 2023 Red Hat

reuse-lint:
  image: docker.io/library/alpine:3
  before_script:
    - apk add git reuse
  script:
    - reuse lint

flake8:
  image: docker.io/library/alpine:3
  before_script:
    - apk add py3-flake8
  script:
    - flake8 --show-source

black:
  image: docker.io/library/alpine:3
  before_script:
    - apk add black
  script:
    - black .

